// Generated by npm run generate --workspace @solventa/assets.
export const brandColors = {
  "green": "#0B6B5F",
  "white": "#FFFFFF",
  "dark": "#062F2A"
} as const;

// Package-relative paths for tools and documentation; use /web or /mobile in apps.
export const assetPaths = {
  "logo": {
    "green": {
      "svg": "brand/solventa-logo-green.svg",
      "png": "brand/solventa-logo-green.png",
      "width": 2012,
      "height": 381,
      "aspectRatio": 5.2808398950131235
    },
    "white": {
      "svg": "brand/solventa-logo-white.svg",
      "png": "brand/solventa-logo-white.png",
      "width": 2012,
      "height": 381,
      "aspectRatio": 5.2808398950131235
    },
    "dark": {
      "svg": "brand/solventa-logo-dark.svg",
      "png": "brand/solventa-logo-dark.png",
      "width": 2012,
      "height": 381,
      "aspectRatio": 5.2808398950131235
    }
  },
  "icon": {
    "green": {
      "svg": "brand/solventa-icon-green.svg",
      "png": "brand/solventa-icon-green.png",
      "width": 424,
      "height": 424,
      "aspectRatio": 1
    },
    "white": {
      "svg": "brand/solventa-icon-white.svg",
      "png": "brand/solventa-icon-white.png",
      "width": 424,
      "height": 424,
      "aspectRatio": 1
    },
    "dark": {
      "svg": "brand/solventa-icon-dark.svg",
      "png": "brand/solventa-icon-dark.png",
      "width": 424,
      "height": 424,
      "aspectRatio": 1
    }
  },
  "wordmark": {
    "green": {
      "svg": "brand/solventa-wordmark-green.svg",
      "png": "brand/solventa-wordmark-green.png",
      "width": 1566,
      "height": 304,
      "aspectRatio": 5.151315789473684
    },
    "white": {
      "svg": "brand/solventa-wordmark-white.svg",
      "png": "brand/solventa-wordmark-white.png",
      "width": 1566,
      "height": 304,
      "aspectRatio": 5.151315789473684
    },
    "dark": {
      "svg": "brand/solventa-wordmark-dark.svg",
      "png": "brand/solventa-wordmark-dark.png",
      "width": 1566,
      "height": 304,
      "aspectRatio": 5.151315789473684
    }
  },
  "stacked": {
    "green": {
      "svg": "brand/solventa-stacked-green.svg",
      "png": "brand/solventa-stacked-green.png",
      "width": 640,
      "height": 500,
      "aspectRatio": 1.28
    },
    "white": {
      "svg": "brand/solventa-stacked-white.svg",
      "png": "brand/solventa-stacked-white.png",
      "width": 640,
      "height": 500,
      "aspectRatio": 1.28
    },
    "dark": {
      "svg": "brand/solventa-stacked-dark.svg",
      "png": "brand/solventa-stacked-dark.png",
      "width": 640,
      "height": 500,
      "aspectRatio": 1.28
    }
  }
} as const;
