// Generated by npm run generate --workspace @solventa/assets.
declare function require(path: string): number;

const logoGreen = require('../brand/solventa-logo-green.png');
const logoWhite = require('../brand/solventa-logo-white.png');
const logoDark = require('../brand/solventa-logo-dark.png');
const iconGreen = require('../brand/solventa-icon-green.png');
const iconWhite = require('../brand/solventa-icon-white.png');
const iconDark = require('../brand/solventa-icon-dark.png');
const wordmarkGreen = require('../brand/solventa-wordmark-green.png');
const wordmarkWhite = require('../brand/solventa-wordmark-white.png');
const wordmarkDark = require('../brand/solventa-wordmark-dark.png');
const stackedGreen = require('../brand/solventa-stacked-green.png');
const stackedWhite = require('../brand/solventa-stacked-white.png');
const stackedDark = require('../brand/solventa-stacked-dark.png');

export const brandAssets = {
  logo: { green: logoGreen, white: logoWhite, dark: logoDark },
  icon: { green: iconGreen, white: iconWhite, dark: iconDark },
  wordmark: { green: wordmarkGreen, white: wordmarkWhite, dark: wordmarkDark },
  stacked: { green: stackedGreen, white: stackedWhite, dark: stackedDark }
} as const;
