// Generated by npm run generate --workspace @solventa/assets.
import logoGreen from '../brand/solventa-logo-green.svg';
import logoWhite from '../brand/solventa-logo-white.svg';
import logoDark from '../brand/solventa-logo-dark.svg';
import iconGreen from '../brand/solventa-icon-green.svg';
import iconWhite from '../brand/solventa-icon-white.svg';
import iconDark from '../brand/solventa-icon-dark.svg';
import wordmarkGreen from '../brand/solventa-wordmark-green.svg';
import wordmarkWhite from '../brand/solventa-wordmark-white.svg';
import wordmarkDark from '../brand/solventa-wordmark-dark.svg';
import stackedGreen from '../brand/solventa-stacked-green.svg';
import stackedWhite from '../brand/solventa-stacked-white.svg';
import stackedDark from '../brand/solventa-stacked-dark.svg';

export const brandAssets = {
  logo: { green: logoGreen, white: logoWhite, dark: logoDark },
  icon: { green: iconGreen, white: iconWhite, dark: iconDark },
  wordmark: { green: wordmarkGreen, white: wordmarkWhite, dark: wordmarkDark },
  stacked: { green: stackedGreen, white: stackedWhite, dark: stackedDark }
} as const;
